language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl
    - LISP=allegro
    - LISP=cmucl

install:
  - curl -L https://raw.githubusercontent.com/fukamachi/roswell/openjdk/scripts/install-for-ci.sh | sh
  - ros install prove

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre
      - clisp

script:
  - run-prove quri-test.asd
